### ISSUE TITLE
Login Failed:  Cannot Connect to authentication server

### ISSUE THREAD

**Issue by nyuuns2** [TechnicianLP/ReAuth#18]
I keep getting consistently de-authenticated and reauth doesn't help. i have no idea why nor had much success in searching the internet.
Here's the log: https://paste.ee/r/GSUY5/0

**Comment by TechnicianLP** [comment]
That is caused by the Cloudflare service rejecting your connection and sending you back HTML telling you that, but the AuthLib is expecting a JSON Response and therefore cannot communicate with the Authentication Services.
I had this exact Issue once developing and restarting your Router to get a new IP-Address fix that for me
