### ISSUE TITLE
Trying to build 1.12.2 version of this and getting error when setupDecompWorkspace

### ISSUE THREAD

**Issue by TheUnderTaker11** [TechnicianLP/ReAuth#20]
I downloaded the exact forge version in your build.gradle in case that was the problem, but it still persisted. 
When running "gradlew setupDecompWorkspace", I get the following error below 
![image](https://user-images.githubusercontent.com/16872377/78472427-4d5e0700-76fe-11ea-840f-c93ae2826da7.png)

I'm just trying to make a super small edit for my personal use (Making Secure class and it's login method public so I can call it when automatically re-logging in with another mod.) So nothing but adding 2 words in two places of the code.

But I'm getting stuck on the fact it errors out due to keyStoreAlias property.

EDIT: I would give stacktrace but I'm not sure where that logs to. I tried re-directing command line output by using "gradlew setupDecompWorkspace --stacktrace > output.txt", but it didn't log anything besides basically saying build failed, all the rest still went to the CMD prompt instead of the text file.

**Comment by TechnicianLP** [comment]
That seems to be caused by my jar-signing code i added to the build.gadle file just delete everything below [this line](https://github.com/TechnicianLP/ReAuth/blob/1.12/build.gradle#L55) for now.
You will also have to make an edit to the Main class to disable the signature check.

Im intrigued as to what your usecase or the other mod could be, can you elaborate on those? I _might_ be able to incorporate this into ReAuth by default.

Keep in mind that this Project is visible source only and you are not permitted to distribute derivatives ie. the modified version of this mod.

**Comment by TheUnderTaker11** [comment]
My use case is to hook it in with another mod like Forge Haxs to make their
auto-rejoin feature also auto-reauth meaning anarchy bots can infinitely
run.

Essentially the "feature" to add would be an auto-rejoin that also auths
you using the saved username + password.

**Comment by TechnicianLP** [comment]
While ReAuth will not be offering fully automatic retries, version 3.9.0 now has a "Login as and Retry" Button on the Connection error Screen. While v3.9.0 is currently only available for 1.16 (Forge and Fabric) backports to older Mc Versions will follow soonish.
