### ISSUE TITLE
Password doesnt get saved when clicking to save it

### ISSUE THREAD

**Issue by WHATS4PP** [TechnicianLP/ReAuth#21]
Title says all. After filling in email and password, clicking the save to config field and logging in afterwards, the passwords wont get saved to config.

**Comment by TechnicianLP** [comment]
Would you be able to provide your log file?

**Comment by WHATS4PP** [comment]
Sure thing. https://pastebin.com/8vLJ9dGb
I think/hope thats all the important stuff from the log, its way too big to paste it all since I have MC running like 24/7

**Comment by TechnicianLP** [comment]
Please update your java 8 installation - Java was enforcing limitations on the allowed strength of cryptographic functions by default (for legal reasons) until Janauary 2018 (Java 8 Update 161). Your issue seems to be caused by this restriction.
If updating java is not an option for you (it shouldnt be) you can alternatively install the "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files"

**Comment by TechnicianLP** [comment]
I have just now been informed that you have installed the java version mojang uses by default - i will therefore support that version an will write a fix shortly

**Comment by TechnicianLP** [comment]
Please test again with version 3.8.1
