### ISSUE TITLE
[Request] Auto Login

### ISSUE THREAD

**Issue by pasi123567** [TechnicianLP/ReAuth#23]
I would love if you could implement a checkmark to automatically reauthenticate when the client gets the information that the session is invalid. 
For example you try to join a server and even though the session is invalid, the mod just authenticates you without noticing and lets you on the server.

**Comment by TechnicianLP** [comment]
While ReAuth will not be offering fully automatic retries, version 3.9.0 now has a "Login as <Username> and Retry" Button on the Connection error Screen. While v3.9.0 is currently only available for 1.16 (Forge and Fabric) backports to older Mc Versions will follow soonish.
I dont like fully automatic retries because the account used could be different to the one stored in the config, which apart from using the Users credentials without their explicit consent, could mean they get silenty switched to a different account.
